/** Provincias / jurisdicciones de Argentina para el wizard de inscripción. */
export const PROVINCIAS_AR = [
  "Ciudad Autónoma de Buenos Aires",
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
] as const

/** Nacionalidades frecuentes en el club (desplegable). */
export const NACIONALIDADES = [
  "Argentina",
  "Boliviana",
  "Brasileña",
  "Chilena",
  "Colombiana",
  "Española",
  "Italiana",
  "Paraguaya",
  "Peruana",
  "Uruguaya",
  "Venezolana",
  "Otra",
] as const
